name: publish

on:
  release:
    types: [created]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: 5.1.5

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: install busted
        run: |
          luarocks install busted

      - name: run tests
        run: |
          busted -o utfTerminal

  publish-to-luarocks:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: upload to Luarocks
        run: |
          location=$(lua genrockspec.lua)
          luarocks upload $location --api-key=${{ secrets.LUAROCKS_KEY }}

      - uses: EndBug/add-and-commit@v5
        with:
          message: 'Upload rockspec'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-to-lit:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: install Luvit
        run: |
          curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh

      - name: store away keys
        run: |
          mkdir -p ~/.ssh
          cat "${{ secrets.LIT_PUBLIC }}" > ~/.ssh/id_rsa.pub
          cat "${{ secrets.LIT_PRIVATE }}" > ~/.ssh/id_rsa

      - name: generate package.lua
        run: |
          lua genpackage.lua

      - name: upload to Lit
        run: |
          lit auth SovietKitsune
          lit publish