name: testing

on: [push, pull_request]

jobs:
  run-busted-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: install dependencies
        run: |
          luarocks install busted

      - name: test
        run: |
          busted -o utfTerminal