name: testing

on: [push]

jobs:
  run-busted-tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.5", "5.4.1", "luajit-2.1.0-beta3"]
    steps:
      - uses: actions/checkout@v2

      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: install dependencies
        run: |
          luarocks install luacov
          luarocks install busted

      - name: test
        run: |
          busted -o utfTerminal -c

      - name: coverage
        run: |
          bash <(curl -s https://codecov.io/bash)